using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;
using System.Text;

namespace Azalea.SourceGeneration;

[Generator]
internal class OpenGLLoadedFunctionGenerator : IIncrementalGenerator
{
	readonly struct OpenGLLoadedFunctionData(string name, string @namespace, string containingClass,
		string returnType, (string, string, RefKind)[] arguments, string glName,
		string? summary, string? alternativeName)
	{
		public string Name { get; } = name;
		public string Namespace { get; } = @namespace;
		public string ContainingClass { get; } = containingClass;
		public string ReturnType { get; } = returnType;
		public (string, string, RefKind)[] Arguments { get; } = arguments;
		public string GlName { get; } = glName;
		public string? Summary { get; } = summary;
		public string? AlternativeName { get; } = alternativeName;
	}

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
			"Azalea.Native.OpenGL.GL+OpenGLLoadedFunctionAttribute",
			predicate: (node, _) => node is DelegateDeclarationSyntax,
			transform: (ctx, _) =>
			{
				var functionAttribute = ctx.Attributes.First(
					a => a.AttributeClass?.Name == "OpenGLLoadedFunctionAttribute");

				var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
				var delegateMethod = symbol.DelegateInvokeMethod!;

				return new OpenGLLoadedFunctionData(
					name: symbol.Name,
					@namespace: symbol.ContainingNamespace.IsGlobalNamespace ?
						string.Empty
						: symbol.ContainingNamespace.ToDisplayString(),
					containingClass: symbol.ContainingSymbol.Name,
					returnType: delegateMethod.ReturnType.ToString(),
					arguments: [..delegateMethod.Parameters
					.Select(p => (p.Type.ToString(), p.Name, p.RefKind))],
					glName: functionAttribute.ConstructorArguments[0].Value!.ToString(),
					summary: functionAttribute.ConstructorArguments[1].Value?.ToString(),
					alternativeName: functionAttribute.ConstructorArguments[2].Value?.ToString());
			});

		context.RegisterSourceOutput(provider.Collect(), (ctx, commands) =>
		{
			var builder = new StringBuilder();
			builder.AppendLine("// <auto-generated/>");

			foreach (var command in commands)
				builder.Append(generateClass(command));

			if (builder.Length <= 25)
				return;

			builder.AppendLine($"namespace {commands[0].Namespace}");
			builder.AppendLine("{");
			builder.AppendLine($"\tpublic static partial class {commands[0].ContainingClass}");
			builder.AppendLine("\t{");
			builder.AppendLine("\t\tpublic static bool DynamicFunctionsLoaded { get; private set; } = false;");
			builder.AppendLine("\t\t/// <summary> A valid OpenGL context must be current before calling this method </summary>");
			builder.AppendLine("\t\tpublic static void LoadDynamicFunctions(Func<string, nint> getProcAddressMethod)");
			builder.AppendLine("\t\t{");

			foreach (var command in commands)
			{
				builder.Append($"\t\t\t__");
				builder.Append(command.Name);
				builder.Append(" = System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer<");
				builder.Append(command.Name);
				builder.Append(">(getProcAddressMethod(\"");
				builder.Append(command.GlName);
				builder.AppendLine("\"));");
			}

			builder.AppendLine("\t\t\tDynamicFunctionsLoaded = true;");
			builder.AppendLine("\t\t}");
			builder.AppendLine("\t}");
			builder.AppendLine("}");

			ctx.AddSource("OpenGLLoadedFunctions.g.cs", builder.ToString());
		});
	}

	private string generateClass(OpenGLLoadedFunctionData command)
	{
		var builder = new StringBuilder();

		int tabIndex = 0;

		// Namespace
		builder.Append("namespace ");
		builder.Append(command.Namespace);
		beginNest();

		builder.Append("public static partial class ");
		builder.Append(command.ContainingClass);
		beginNest();

		builder.Append($"private static {command.Name}? __{command.Name};");
		newLine();
		if (command.Summary is not null)
		{
			builder.Append("/// <summary>");
			builder.Append(command.Summary);
			builder.Append("</summary>");
			newLine();
		}

		builder.Append($"public static {command.ReturnType} ");
		builder.Append(command.AlternativeName is not null
			? command.AlternativeName
			: command.Name.Substring(0, command.Name.Length - 8));
		builder.Append('(');
		appendAllParameters();
		builder.Append($") => __{command.Name}!(");
		appendAllParameters(types: false);
		builder.Append(");");

		endNest();
		endNest();
		newLine();

		return builder.ToString();

		void newLine()
		{
			builder.Append('\n');

			for (int i = 0; i < tabIndex; i++)
				builder.Append('\t');
		}

		void beginNest()
		{
			newLine();
			builder.Append('{');
			tabIndex++;
			newLine();
		}

		void endNest()
		{
			tabIndex--;
			newLine();
			builder.Append('}');
		}

		void appendAllParameters(bool types = true)
		{
			for (int i = 0; i < command.Arguments.Length; i++)
			{
				var type = command.Arguments[i].Item1;
				var name = command.Arguments[i].Item2;
				var refKind = command.Arguments[i].Item3;

				switch (refKind)
				{
					case RefKind.None: break;
					case RefKind.In:
						builder.Append("in "); break;
					case RefKind.Out:
						builder.Append("out "); break;
					case RefKind.Ref:
						builder.Append("ref "); break;
				}

				if (types)
				{
					builder.Append(type);
					builder.Append(' ');
				}

				builder.Append(name);

				if (i + 1 < command.Arguments.Length)
					builder.Append(", ");
			}
		}
	}

	private string generateInitializations(string @namespace, string containingClass)
	{
		var builder = new StringBuilder();

		int tabIndex = 0;

		// Namespace
		builder.Append($"namespace {@namespace}");
		beginNest();

		builder.Append($"public static partial class {containingClass}");
		beginNest();

		endNest();
		endNest();
		newLine();

		return builder.ToString();

		void newLine()
		{
			builder.Append('\n');

			for (int i = 0; i < tabIndex; i++)
				builder.Append('\t');
		}

		void beginNest()
		{
			newLine();
			builder.Append('{');
			tabIndex++;
			newLine();
		}

		void endNest()
		{
			tabIndex--;
			newLine();
			builder.Append('}');
		}
	}
}
