using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Azalea.SourceGeneration;

[Generator]
internal class RenderCommandGenerator : IIncrementalGenerator
{
	struct RenderCommandData(string name, string @namespace, Accessibility accessModifier,
		List<(string, string)> properties)
	{
		public string Name { get; set; } = name;
		public string Namespace { get; set; } = @namespace;
		public Accessibility AccessModifier { get; set; } = accessModifier;
		public List<(string, string)> Properties { get; set; } = properties;
	}

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
			"Azalea.Platform.Rendering.RenderCommandAttribute",
			predicate: (node, _) => node is ClassDeclarationSyntax,
			transform: (ctx, _) =>
			{
				var symbol = (INamedTypeSymbol)ctx.TargetSymbol;

				return new RenderCommandData(
					name: symbol.Name,
					@namespace: symbol.ContainingNamespace.IsGlobalNamespace ?
						string.Empty
						: symbol.ContainingNamespace.ToDisplayString(),
					accessModifier: symbol.DeclaredAccessibility,
					properties: [.. symbol.GetMembers()
					.OfType<IFieldSymbol>()
					.Select(p => (p.Type.ToDisplayString(), p.Name))]);
			});

		context.RegisterSourceOutput(provider.Collect(), (ctx, commands) =>
		{
			var builder = new StringBuilder();
			builder.AppendLine("// <auto-generated/>");

			foreach (var command in commands)
				builder.Append(generateClass(command));

			if (builder.Length <= 25)
				return;

			ctx.AddSource("RenderCommands.g.cs", builder.ToString());
		});
	}

	private string generateClass(RenderCommandData command)
	{
		var builder = new StringBuilder();

		int tabIndex = 0;

		// Namespace
		builder.Append("namespace ");
		builder.Append(command.Namespace);
		beginNest();

		// Class
		builder.Append(command.AccessModifier switch
		{
			Accessibility.Private => "private",
			Accessibility.Public => "public ",
			Accessibility.Internal => "internal",
			_ => "public"
		});

		builder.Append(" partial class ");
		builder.Append(command.Name);
		beginNest();

		// Constructor
		builder.Append("private ");
		builder.Append(command.Name);
		builder.Append('(');
		appendAllParameters();
		builder.Append(')');
		beginNest();

		for (int i = 0; i < command.Properties.Count; i++)
		{
			var name = command.Properties[i].Item2;

			builder.Append(name);
			builder.Append(" = ");
			builder.Append("__");
			builder.Append(name);
			builder.Append(';');

			if (i + 1 < command.Properties.Count)
				newLine();
		}

		endNest();
		newLine();

		// CommandPool
		builder.Append("private static readonly System.Collections.Concurrent.ConcurrentBag<");
		builder.Append(command.Name);
		builder.Append("> __commandPool = new();");
		newLine();

		// Populate

		// Borrow Method
		builder.Append("public static ");
		builder.Append(command.Name);
		builder.Append(" Borrow(");
		appendAllParameters();
		builder.Append(")");
		beginNest();

		builder.Append("if (__commandPool.TryTake(out var command))");
		beginNest();

		foreach (var property in command.Properties)
		{
			builder.Append("command.");
			builder.Append(property.Item2);
			builder.Append(" = __");
			builder.Append(property.Item2);
			builder.Append(';');
			newLine();
		}

		builder.Append("return command;");
		endNest();
		newLine();

		builder.Append("return new ");
		builder.Append(command.Name);
		builder.Append('(');
		appendAllParameters(types: false);
		builder.Append(");");

		endNest();
		newLine();

		// Return
		builder.Append("public override void Return() => __commandPool.Add(this);");
		newLine();

		// Deconstruc Method
		builder.Append("public void Deconstruct(");
		appendAllParameters(@out: true);
		builder.Append(")");
		beginNest();

		for (int i = 0; i < command.Properties.Count; i++)
		{
			var name = command.Properties[i].Item2;

			builder.Append("__");
			builder.Append(name);
			builder.Append(" = ");
			builder.Append(name);
			builder.Append(';');

			if (i + 1 < command.Properties.Count)
				newLine();
		}

		endNest();
		endNest();
		endNest();
		newLine();

		return builder.ToString();

		void newLine()
		{
			builder.Append('\n');

			for (int i = 0; i < tabIndex; i++)
				builder.Append('\t');
		}

		void beginNest()
		{
			newLine();
			builder.Append('{');
			tabIndex++;
			newLine();
		}

		void endNest()
		{
			tabIndex--;
			newLine();
			builder.Append('}');
		}

		void appendAllParameters(bool types = true, bool @out = false)
		{
			for (int i = 0; i < command.Properties.Count; i++)
			{
				var type = command.Properties[i].Item1;
				var name = command.Properties[i].Item2;

				if (@out)
					builder.Append("out ");

				if (types)
				{
					builder.Append(type);
					builder.Append(' ');
				}

				builder.Append("__");
				builder.Append(name);

				if (i + 1 < command.Properties.Count)
					builder.Append(", ");
			}
		}
	}
}
