using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Azalea.SourceGeneration;

[Generator]
internal class ThreadCommandGenerator : IIncrementalGenerator
{
	readonly struct ThreadCommandData(string name, string @namespace,
		Accessibility accessModifier, string parentClass, bool awaitable,
		bool generateHandler, string? displayName, List<(string, string)> properties)
	{
		public string Name { get; } = name;
		public string Namespace { get; } = @namespace;
		public Accessibility AccessModifier { get; } = accessModifier;
		public string ParentClass { get; } = parentClass;
		public bool Awaitable { get; } = awaitable;
		public bool GenerateHandler { get; } = generateHandler;
		public string DisplayName { get; } = displayName is not null ? displayName :
			(name.EndsWith("Command") ? name.Substring(0, name.Length - 7) : name);
		public List<(string, string)> Properties { get; } = properties;
	}

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
			"Azalea.Threading.ThreadCommandAttribute",
			predicate: (node, _) => node is ClassDeclarationSyntax,
			transform: (ctx, _) =>
			{
				var functionAttribute = ctx.Attributes.First(
					a => a.AttributeClass?.Name == "ThreadCommandAttribute");

				var symbol = (INamedTypeSymbol)ctx.TargetSymbol;

				return new ThreadCommandData(
					name: symbol.Name,
					@namespace: symbol.ContainingNamespace.IsGlobalNamespace ?
						string.Empty
						: symbol.ContainingNamespace.ToDisplayString(),
					accessModifier: symbol.DeclaredAccessibility,
					parentClass: symbol.BaseType!.Name,
					awaitable: (bool)functionAttribute.ConstructorArguments[0].Value!,
					generateHandler: (bool)functionAttribute.ConstructorArguments[1].Value!,
					displayName: (string?)functionAttribute.ConstructorArguments[2].Value!,
					properties: [.. symbol.GetMembers()
					.OfType<IFieldSymbol>()
					.Select(p => (p.Type.ToDisplayString(), p.Name))]);
			});

		context.RegisterSourceOutput(provider.Collect(), (ctx, commands) =>
		{
			var builder = new StringBuilder();
			builder.AppendLine("// <auto-generated/>");

			foreach (var command in commands)
				builder.Append(generateClass(command));

			if (builder.Length <= 25)
				return;

			ctx.AddSource("ThreadCommands.g.cs", builder.ToString());
		});
	}

	private string generateClass(ThreadCommandData command)
	{
		var builder = new StringBuilder();

		int tabIndex = 0;

		// Namespace
		builder.Append("namespace ");
		builder.Append(command.Namespace);
		beginNest();

		// Class
		appendAccessModifier(command.AccessModifier);
		builder.Append(" partial class ");
		builder.Append(command.Name);
		if (command.Awaitable)
			builder.Append(" : Azalea.Threading.ICommandAwaitable");

		beginNest();

		// Constructor
		builder.Append("private ");
		builder.Append(command.Name);
		builder.Append('(');
		appendAllParameters();
		builder.Append(')');
		beginNest();

		builder.Append("TotalCreated++;");
		newLine();

		for (int i = 0; i < command.Properties.Count; i++)
		{
			var name = command.Properties[i].Item2;

			builder.Append(name);
			builder.Append(" = ");
			builder.Append("__");
			builder.Append(name);
			builder.Append(';');

			if (i + 1 < command.Properties.Count)
				newLine();
		}

		builder.Append("OnCommandCreated?.Invoke(this);");
		newLine();

		endNest();
		newLine();

		// CommandPool
		builder.Append("private static readonly System.Collections.Concurrent.ConcurrentBag<");
		builder.Append(command.Name);
		builder.Append("> __commandPool = new();");
		newLine();

		// TotalCreated
		builder.Append("internal static volatile new int TotalCreated = 0;");
		newLine();

		// Borrow Method
		builder.Append("public static ");
		builder.Append(command.Name);
		builder.Append(" Borrow(");
		appendAllParameters();
		builder.Append(")");
		beginNest();

		builder.Append("if (__commandPool.TryTake(out var command))");
		beginNest();

		foreach (var property in command.Properties)
		{
			builder.Append("command.");
			builder.Append(property.Item2);
			builder.Append(" = __");
			builder.Append(property.Item2);
			builder.Append(';');
			newLine();
		}

		builder.Append("return command;");
		endNest();
		newLine();

		builder.Append("return new ");
		builder.Append(command.Name);
		builder.Append('(');
		appendAllParameters(types: false);
		builder.Append(");");

		endNest();
		newLine();

		// Return
		builder.Append("public override void Return()");
		beginNest();
		builder.Append("Cleanup();");
		newLine();
		if (command.Awaitable)
		{
			builder.Append("_completedEvent.Set();");
			newLine();
			builder.Append("_completedEvent.Reset();");
			newLine();
		}
		builder.Append("__commandPool.Add(this);");
		endNest();
		newLine();

		// Deconstruc Method
		builder.Append("public void Deconstruct(");
		appendAllParameters(@out: true);
		builder.Append(")");
		beginNest();

		for (int i = 0; i < command.Properties.Count; i++)
		{
			var name = command.Properties[i].Item2;

			builder.Append("__");
			builder.Append(name);
			builder.Append(" = ");
			builder.Append(name);
			builder.Append(';');

			if (i + 1 < command.Properties.Count)
				newLine();
		}
		endNest();

		if (command.Awaitable)
		{
			newLine();

			// ManualResetEvent
			builder.Append("private readonly System.Threading.ManualResetEvent _completedEvent = new(false);");
			newLine();

			// Await Method
			builder.Append("public void Await() => _completedEvent.WaitOne();");
		}

		endNest();

		if (command.GenerateHandler)
		{
			newLine();
			builder.Append($"public static class {command.Name}_Handler");
			beginNest();
			builder.Append($"public static {(command.Awaitable ? "Azalea.Threading.ICommandAwaitable" : "void")} {command.DisplayName}(this Azalea.Threading.ICommandHandler<{command.ParentClass}> handler");

			if (command.Properties.Count > 0)
			{
				builder.Append(", ");
				appendAllParameters();
			}

			builder.Append(")");
			newLine();
			builder.Append($"\t=> handler.Enqueue({command.Name}.Borrow(");
			appendAllParameters(types: false);
			builder.Append("));");
			endNest();
		}

		endNest();

		newLine();

		return builder.ToString();

		void newLine()
		{
			builder.Append('\n');

			for (int i = 0; i < tabIndex; i++)
				builder.Append('\t');
		}

		void beginNest()
		{
			newLine();
			builder.Append('{');
			tabIndex++;
			newLine();
		}

		void endNest()
		{
			tabIndex--;
			newLine();
			builder.Append('}');
		}

		void appendAllParameters(bool types = true, bool @out = false)
		{
			for (int i = 0; i < command.Properties.Count; i++)
			{
				var type = command.Properties[i].Item1;
				var name = command.Properties[i].Item2;

				if (@out)
					builder.Append("out ");

				if (types)
				{
					builder.Append(type);
					builder.Append(' ');
				}

				builder.Append("__");
				builder.Append(name);

				if (i + 1 < command.Properties.Count)
					builder.Append(", ");
			}
		}

		void appendAccessModifier(Accessibility accessibility)
		{
			builder.Append(accessibility switch
			{
				Accessibility.Private => "private",
				Accessibility.Public => "public ",
				Accessibility.Internal => "internal",
				_ => "public"
			});
		}
	}
}
