using Azalea.Design.Containers;
using Azalea.Design.Controls;
using Azalea.Design.UserInterface;
using Azalea.Design.UserInterface.Basic;
using Azalea.Graphics;
using Azalea.Graphics.Colors;
using Azalea.Graphics.Sprites;
using System;
using System.Diagnostics;
using System.IO;
using System.Text;

namespace Azalea.Editor.Views.MsdfGen;
internal class MsdfGenView : Composition
{
	private int _size = 48;
	private string _charsFileName = "__msdfCharsAutoGenerated.txt";

	private FileInputControl _fontInputControl;
	private FileInputControl _outputDirectoryControl;
	private TextBoxControl _characterSetControl;
	private DropDownMenuControl _modeControl;

	private FlexContainer _outputTextContainer;

	public MsdfGenView()
	{
		Add(new FlexContainer()
		{
			Direction = FlexDirection.Vertical,
			RelativeSizeAxes = Axes.Both,
			Padding = new(26),
			Children = [
				new LabelControl(){
					Text = "Input font:",
					Depth = 0,
				},
				_fontInputControl = new FileInputControl(){
					Depth = 1,
				},
				new FormTextControl(){
					Text = "Drag a file over the control to select it.",
					Depth = 2
				},
				new LabelControl(){
					Text = "Output directory:",
					Depth = 3
				},
				_outputDirectoryControl = new FileInputControl(){
					AcceptedFiles = AcceptedFileFlags.Directory,
					Depth = 4
				},
				new FormTextControl(){
					Text = "Drag a directory over the control to select it.",
					Depth = 5
				},
				new LabelControl(){
					Text = "Character set:",
					Depth = 6
				},
				_characterSetControl = new TextBoxControl(){
					Text = "[0x21, 0x7A]",
					Depth = 7,
				},
				new FormTextControl(){
					Text = "A comma separated list like: 'A', 'B', \"ABC\", ['A', 'Z'], [65, 90]; or [0x21, 0x7A] for all ASCII characters and [0x0, 0xFFFF] for all characters",
					Depth = 8
				},
				new LabelControl(){
					Text = $"Mode:",
					Depth = 9
				},
				_modeControl = new DropDownMenuControl(){
					RelativeSizeAxes = Axes.None,
					Width = 300,
					Values = ["Hardmask", "Softmask", "Sdf", "Pdsf", "Msdf", "Mtsdf"],
					SelectedValue = "Msdf",
					Depth = 10
				},
				new LabelControl(){
					Text = $"Size: {_size}",
					Depth = 11
				},
				new ButtonControl(){
					Text = "Generate",
					ClickAction = _ => generate(_fontInputControl.SelectedPath,
						_outputDirectoryControl.SelectedPath, _size, _modeControl.SelectedValue),
					Margin = new(16, 0, 16, 0),
					Depth = 12
				},
				_outputTextContainer = new FlexContainer(){
					RelativeSizeAxes = Axes.X,
					AutoSizeAxes = Axes.Y,
					Margin = new(16, 0, 0, 0),
					Direction = FlexDirection.Vertical,
					Depth = 13
				}
			]
		});
	}

	private void generate(string? fontPath, string? outputPath, int size, string mode, string? outputFileName = null)
	{
		_outputTextContainer.Clear();

		if (fontPath is null)
		{
			outputString("Input font must be provided!");
			return;
		}

		outputPath ??= Path.GetDirectoryName(fontPath);
		outputFileName ??= Path.GetFileNameWithoutExtension(fontPath);

		if (Directory.Exists(outputPath) == false)
			Directory.CreateDirectory(outputPath!);

		var args = new StringBuilder();
		#region MsdfGen
		/*if (fontPath.EndsWith(".ttf"))
		{
			args.Append("-font ");
			args.Append(fontPath);
			args.Append(' ');
		}
		else if (fontPath.EndsWith(".svg"))
		{
			args.Append("-svg ");
			args.Append(fontPath);
			args.Append(' ');
		}
		else
		{
			outputString("Unknown input format!");
			return;
		}

		args.Append(mode.ToLower());
		args.Append(' ');

		args.Append("-o ");
		args.Append(outputPath);
		args.Append('\\');
		args.Append(outputFileName);
		args.Append(".bmp ");

		args.Append("-size ");
		args.Append(size);
		args.Append(' ');
		args.Append(size);
		args.Append(' ');

		args.Append("-pxrange 4 ");

		var process = new Process()
		{
			StartInfo = new()
			{
				FileName = @"bin\msdfgen.exe",
				Arguments = args.ToString(),
				UseShellExecute = false,
				RedirectStandardOutput = true,
				RedirectStandardError = true,
				CreateNoWindow = true
			}
		};*/
		#endregion
		#region MsdfAtlasGen
		if (fontPath.EndsWith(".ttf"))
		{
			args.Append("-font ");
			args.Append(fontPath);
			args.Append(' ');
		}
		else if (fontPath.EndsWith(".svg"))
		{
			args.Append("-svg ");
			args.Append(fontPath);
			args.Append(' ');
		}
		else
		{
			outputString("Unknown input format!");
			return;
		}

		args.Append("-type ");
		args.Append(mode.ToLower());
		args.Append(' ');

		args.Append("-charset ");
		args.Append(_charsFileName);
		args.Append(' ');

		args.Append("-imageout ");
		args.Append(outputPath);
		args.Append('\\');
		args.Append(outputFileName);
		args.Append(".bmp ");

		args.Append("-csv ");
		args.Append(outputPath);
		args.Append('\\');
		args.Append(outputFileName);
		args.Append(".csv ");

		args.Append("-size ");
		args.Append(size);
		args.Append(' ');

		args.Append("-yorigin top");

		var process = new Process()
		{
			StartInfo = new()
			{
				FileName = @"bin\msdf-atlas-gen.exe",
				Arguments = args.ToString(),
				UseShellExecute = false,
				RedirectStandardOutput = true,
				RedirectStandardError = true,
				CreateNoWindow = true
			}
		};
		#endregion

		// Create a chars.txt file
		var charsPath = Path.Combine(AppContext.BaseDirectory, _charsFileName);
		var charsWriter = File.CreateText(charsPath);
		charsWriter.Write(_characterSetControl.Text);
		charsWriter.Dispose();

		process.Start();

		var imageCreated = false;
		var layoutCreated = false;

		while (!process.StandardError.EndOfStream)
		{
			var line = process.StandardError.ReadLine();
			if (string.IsNullOrWhiteSpace(line))
				continue;

			if (line == "Atlas image file saved.")
			{
				imageCreated = true;
				continue;
			}

			if (line == "Glyph layout written into CSV file.")
			{
				layoutCreated = true;
				continue;
			}

			outputString(line);
		}

		if (imageCreated && layoutCreated)
			outputString("Font atlas generated successfully.");
		else
			outputString("Font atlas could not be generated.");

		// Delete chars.txt file
		if (File.Exists(charsPath))
			File.Delete(charsPath);
	}

	private void outputString(string str)
	{
		_outputTextContainer.Add(new LabelControl()
		{
			Text = str,
			Margin = new Boundary(4, 0, 4, 0)
		});
	}

	private class LabelControl : SpriteText
	{
		public LabelControl()
		{
			Font = FontUsage.Default.With(size: 16);
			Color = ControlConstants.DarkTextColor;
			Margin = new Boundary(20, 0, 14, 0);
		}
	}

	private class FormTextControl : SpriteText
	{
		public FormTextControl()
		{
			Font = FontUsage.Default.With(size: 14);
			Color = new Color(108, 117, 125);
			Margin = new Boundary(8, 0, 8, 0);
		}
	}

	private class ButtonControl : BasicButton
	{
		public ButtonControl()
		{
			Size = new(92, 38);
			BackgroundColor = new Color(13, 110, 253);
			HoveredColor = new Color(11, 94, 215);
			TextColor = Palette.White;
			FontSize = 16;
		}
	}

	private class TextBoxControl : BasicTextBox
	{
		public TextBoxControl()
			: base(t =>
			{
				t.Color = ControlConstants.DarkTextColor;
				t.Font = ControlConstants.NormalFont;
			})
		{
			Height = ControlConstants.InputControlHeight;
			Width = 700;
			BorderColor = ControlConstants.DarkControlColor;
			BorderThickness = 1;
			Alignment = FlexAlignment.Center;
			Wrapping = FlexWrapping.NoWrapping;
			CaratColor = ControlConstants.DarkTextColor;
			Padding = 10;
		}
	}
}
