using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Reflection.Metadata.Ecma335;
using System.Text;

namespace Azalea.SourceGeneration;

internal class SourceBuilder
{
	private StringBuilder _builder;
	private int _tabIndex = 0;

	public SourceBuilder()
	{
		_builder = new StringBuilder();
		_builder.AppendLine("// <auto-generated/>");
	}

	public void NewLine()
	{
		_builder.Append('\n');

		for (int i = 0; i < _tabIndex; i++)
			_builder.Append('\t');
	}

	public void AppendAccessibility(Accessibility accessibility)
	{
		_builder.Append(accessibility switch
		{
			Accessibility.Private => "private ",
			Accessibility.Public => "public ",
			Accessibility.Internal => "internal ",
			_ => "public "
		});
	}

	public void Append(string value) => _builder.Append(value);
	public void AppendLine(string value)
	{
		Append(value);
		NewLine();
	}

	public void BeginScope()
	{
		NewLine();
		_builder.Append('{');
		_tabIndex++;
		NewLine();
	}

	public void EndScope()
	{
		_tabIndex--;
		NewLine();
		_builder.Append('}');
	}

	public void BeginNamespace(string @namespace)
	{
		Append($"namespace ");
		Append(@namespace);
		BeginScope();
	}

	public void BeginClass(Details details)
	{
		for (int i = details.ContainingDetails.Length - 1; i >= 0; i--)
			BeginClass(details.ContainingDetails[i]);

		AppendAccessibility(details.AccessModifier);
		Append("partial ");

		switch (details.Kind)
		{
			case TypeKind.Class:
				Append("class ");
				break;
			case TypeKind.Interface:
				Append("interface ");
				break;
			default:
				throw new NotImplementedException($"Kind `{details.Kind}` not implemented.");
		}

		Append(details.Name);
		BeginScope();
	}

	public void BeginClass(ImmutableArray<Details> containingDetails)
	{
		for (int i = containingDetails.Length - 1; i >= 0; i--)
			BeginClass(containingDetails[i]);
	}

	public void EndClass(ImmutableArray<Details> containingDetails)
	{
		for (int i = 0; i < containingDetails.Length; i++)
			EndScope();
	}

	public override string ToString() => _builder.ToString();
}
